spring.application.name=flag-trip
server.port=${PORT:8080}
server.compression.enabled=true
server.compression.mime-types=text/html,text/css,application/javascript,application/json,image/svg+xml
spring.web.resources.cache.cachecontrol.max-age=1h
